### ISSUE TITLE
autobahn: Compression tests failing

### ISSUE THREAD

**Issue by pushkarnk** [IBM-Swift/Kitura-WebSocket#88]
Both, the 12.x.x and 13.x.x tests fail with this exception on the client side. The server side doesn't show any error symptoms:
```
Servers = [u'ws://127.0.0.1:9001']
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/autobahntestsuite/wstest.py", line 346, in run
    start(options, spec)
  File "/usr/local/lib/python2.7/dist-packages/autobahntestsuite/wstest.py", line 280, in start
    reactor.run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1267, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1276, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 902, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 520, in connectionLost
    self.connector.connectionLost(reason)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1160, in connectionLost
    self.factory.clientConnectionLost(self, reason)
  File "/usr/local/lib/python2.7/dist-packages/autobahntestsuite/fuzzing.py", line 1292, in clientConnectionLost
    self.createReports()
  File "/usr/local/lib/python2.7/dist-packages/autobahntestsuite/fuzzing.py", line 469, in createReports
    self.createMasterReportHTML(self.outdir)
  File "/usr/local/lib/python2.7/dist-packages/autobahntestsuite/fuzzing.py", line 670, in createMasterReportHTML
    agent_case_report_file = self.makeAgentCaseReportFilename(agentId, caseId, ext = 'html')
  File "/usr/local/lib/python2.7/dist-packages/autobahntestsuite/fuzzing.py", line 498, in makeAgentCaseReportFilename
    return self.cleanForFilename(agentId) + "_case_" + c + "." + ext
  File "/usr/local/lib/python2.7/dist-packages/autobahntestsuite/fuzzing.py", line 487, in cleanForFilename
    s0 = ''.join([c if c in "abcdefghjiklmnopqrstuvwxyz0123456789" else " " for c in str.strip().lower()])
exceptions.AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by pushkarnk** [comment]
Raised a[ pull request ](https://github.com/IBM-Swift/Kitura-WebSocket/pull/90)on `Kitura-WebSocket/websocket-nio` the changes related to which were later pulled to `Kitura-WebSocket-NIO`
